#!/usr/bin/env python3


'''
cd-hit -i final/IGHV.fa -o cd-hit/IGHV.fa -s 0.75
cd-hit -i final/IGLV.fa -o cd-hit/IGLV.fa -s 0.75
'''


import os
from Bio import SeqIO
from Bio.Seq import Seq


with open('cd-hit/IGHV.fa.clstr', 'r') as f:
    clusters = f.read().split('>Cluster ')[1:]

